/** Base task definitions for the original business prompt generator. */

export interface BusinessTaskDef {
  title: string
  section: string
  role: string
  deliverable: string
  steps: string[]
  constraints?: string[]
  outputFormat?: string
  models?: string[]
  type?: 'text' | 'image'
}

export const BUSINESS_AUDIENCES = [
  'B2B enterprise clients',
  'B2C consumer brands',
  'local service businesses',
  'SaaS startups',
  'agency client accounts',
  'solopreneurs and creators',
] as const

export const BUSINESS_STYLES = [
  'detailed and comprehensive',
  'concise and action-oriented',
  'beginner-friendly with explanations',
  'expert-level with advanced tactics',
  'executive summary style',
] as const

export const BUSINESS_SECTIONS: Record<string, { name: string; emoji: string; defaultRole: string; categoryIds: string[] }> = {
  marketing: { name: 'Marketing', emoji: '📣', defaultRole: 'senior marketing strategist with campaign and brand experience', categoryIds: ['marketing', 'business'] },
  sales: { name: 'Sales', emoji: '💰', defaultRole: 'sales enablement expert who builds repeatable revenue systems', categoryIds: ['sales', 'business'] },
  seo: { name: 'SEO', emoji: '🔍', defaultRole: 'technical SEO specialist focused on organic growth', categoryIds: ['seo', 'marketing'] },
  email: { name: 'Email', emoji: '📧', defaultRole: 'email marketing strategist specializing in lifecycle campaigns', categoryIds: ['email', 'marketing'] },
  writing: { name: 'Writing & Content', emoji: '✍️', defaultRole: 'content strategist and professional copywriter', categoryIds: ['writing', 'content'] },
  business: { name: 'Business Strategy', emoji: '💼', defaultRole: 'management consultant who advises founders and operators', categoryIds: ['business', 'productivity'] },
  hr: { name: 'HR & Recruiting', emoji: '👥', defaultRole: 'talent acquisition and people operations expert', categoryIds: ['hr', 'business'] },
  finance: { name: 'Finance', emoji: '💵', defaultRole: 'financial analyst who translates numbers into decisions', categoryIds: ['finance', 'business'] },
  legal: { name: 'Legal & Compliance', emoji: '⚖️', defaultRole: 'business attorney focused on practical commercial guidance', categoryIds: ['legal', 'business'] },
  'customer-service': { name: 'Customer Service', emoji: '🎧', defaultRole: 'customer experience leader who designs support systems', categoryIds: ['customer-service', 'business'] },
  ecommerce: { name: 'E-commerce', emoji: '🛒', defaultRole: 'e-commerce growth specialist with conversion optimization expertise', categoryIds: ['ecommerce', 'business'] },
  productivity: { name: 'Productivity', emoji: '⚡', defaultRole: 'operations consultant who eliminates friction from workflows', categoryIds: ['productivity', 'business'] },
  'social-media': { name: 'Social Media', emoji: '📱', defaultRole: 'social media manager who builds engaged communities', categoryIds: ['social-media', 'marketing'] },
  coding: { name: 'Coding & Tech', emoji: '💻', defaultRole: 'senior software engineer and technical architect', categoryIds: ['coding', 'productivity'] },
  'real-estate': { name: 'Real Estate', emoji: '🏠', defaultRole: 'real estate marketing and transaction specialist', categoryIds: ['real-estate', 'business'] },
}

function stepsFor(deliverable: string, extras: string[] = []): string[] {
  return [
    `Confirm scope: verify the goal for "${deliverable}" and who it serves ({{target-audience}}).`,
    `Use context: apply details about {{company-name}}, {{industry}}, and {{primary-goal}}.`,
    `Produce the ${deliverable} with concrete recommendations — avoid vague or generic advice.`,
    ...extras,
    `Include success metrics or KPIs so results can be measured.`,
    `Close with 3 immediate next actions the user can take today.`,
  ]
}

function mk(
  section: string,
  title: string,
  deliverable: string,
  role?: string,
  extraSteps: string[] = [],
  constraints: string[] = []
): BusinessTaskDef {
  const sec = BUSINESS_SECTIONS[section]
  return {
    title,
    section,
    role: role ?? sec.defaultRole,
    deliverable,
    steps: stepsFor(deliverable, extraSteps),
    constraints: constraints.length ? constraints : ['Stay specific to the business context provided', 'Do not invent facts about the company'],
    outputFormat: `Structured ${deliverable} with clear headings, bullet points where helpful, and a summary section at the top.`,
    models: ['ChatGPT', 'Claude', 'Gemini'],
    type: 'text',
  }
}

/** ~200 base business tasks across 15 sections */
export const BUSINESS_TASK_CATALOG: BusinessTaskDef[] = [
  // Marketing (35)
  mk('marketing', 'Campaign Brief Generator', 'integrated marketing campaign brief', undefined, ['Define target segment, channels, budget allocation, and timeline.']),
  mk('marketing', 'Brand Voice Guide Creator', 'brand voice and tone guide', undefined, ['Include vocabulary to use, words to avoid, and 4 in-voice copy examples.']),
  mk('marketing', 'Content Calendar Builder', '90-day content calendar', undefined, ['Map themes, formats, and publishing cadence by channel.']),
  mk('marketing', 'Ad Copy Variation Generator', '10 ad copy variations for A/B testing', undefined, ['Use different angles: benefit, pain, social proof, urgency.']),
  mk('marketing', 'Landing Page Copy Writer', 'high-converting landing page copy', undefined, ['Cover hero, benefits, social proof, FAQ, and CTA sections.']),
  mk('marketing', 'Competitor Analysis Framework', 'competitive positioning analysis', undefined, ['Compare messaging, offers, channels, and gaps.']),
  mk('marketing', 'Customer Persona Builder', 'detailed buyer persona document', undefined, ['Include demographics, psychographics, pain points, and buying triggers.']),
  mk('marketing', 'Value Proposition Canvas', 'value proposition statement and canvas', undefined, ['Map jobs, pains, gains, and differentiators.']),
  mk('marketing', 'Go-To-Market Plan', 'go-to-market launch plan', undefined, ['Cover positioning, channels, launch timeline, and success metrics.']),
  mk('marketing', 'Growth Experiment Designer', 'prioritized growth experiment backlog', undefined, ['Rank by ICE score: impact, confidence, ease.']),
  mk('marketing', 'Referral Program Designer', 'customer referral program structure', undefined, ['Define incentives, mechanics, and promotion plan.']),
  mk('marketing', 'Influencer Outreach Template', 'influencer partnership pitch and brief', undefined, ['Include deliverables, compensation options, and brand guidelines.']),
  mk('marketing', 'Webinar Promotion Plan', 'webinar promotion and follow-up sequence', undefined, ['Cover pre-event, live, and post-event touchpoints.']),
  mk('marketing', 'Case Study Writer', 'customer success case study', undefined, ['Use challenge-solution-results format with quotes placeholders.']),
  mk('marketing', 'Press Release Draft', 'newsworthy press release', undefined, ['Follow inverted pyramid; include boilerplate and media contact block.']),
  mk('marketing', 'Brand Story Narrative', 'founder or brand origin story', undefined, ['Connect mission, customer problem, and transformation arc.']),
  mk('marketing', 'Marketing Budget Allocator', 'channel budget allocation plan', undefined, ['Split budget by channel with expected ROAS assumptions.']),
  mk('marketing', 'Retargeting Strategy Builder', 'retargeting audience and creative strategy', undefined, ['Segment by funnel stage and intent signals.']),
  mk('marketing', 'Product Launch Checklist', 'product launch marketing checklist', undefined, ['Organize by pre-launch, launch day, and post-launch.']),
  mk('marketing', 'Community Building Playbook', 'online community growth playbook', undefined, ['Define platform, rituals, moderation, and engagement loops.']),
  mk('marketing', 'Partnership Co-Marketing Plan', 'co-marketing partnership proposal', undefined, ['Align audiences, shared goals, and mutual deliverables.']),
  mk('marketing', 'Customer Journey Mapper', 'customer journey map with touchpoints', undefined, ['Mark awareness, consideration, decision, retention stages.']),
  mk('marketing', 'Brand Positioning Statement', 'positioning statement and messaging hierarchy', undefined, ['Include tagline options and proof points.']),
  mk('marketing', 'Event Marketing Plan', 'event promotion and attendance plan', undefined, ['Cover pre-event buzz, onsite activation, and follow-up.']),
  mk('marketing', 'Thought Leadership Outline', 'thought leadership article or talk outline', undefined, ['Anchor on a contrarian or insight-driven thesis.']),
  mk('marketing', 'Marketing ROI Calculator Guide', 'marketing ROI measurement framework', undefined, ['Define attribution model and reporting cadence.']),
  mk('marketing', 'Crisis Communication Plan', 'crisis communication response plan', undefined, ['Include holding statements and escalation paths.']),
  mk('marketing', 'Brand Audit Checklist', 'brand consistency audit checklist', undefined, ['Review visual identity, voice, and channel alignment.']),
  mk('marketing', 'Lead Magnet Idea Generator', 'lead magnet concepts with titles and outlines', undefined, ['Rank by perceived value and production effort.']),
  mk('marketing', 'Affiliate Program Blueprint', 'affiliate or partner program structure', undefined, ['Define commission tiers, tracking, and terms.']),
  mk('marketing', 'Video Marketing Script', 'short-form video marketing script', undefined, ['Hook in first 3 seconds; clear CTA at end.']),
  mk('marketing', 'Podcast Sponsorship Pitch', 'podcast sponsorship pitch deck outline', undefined, ['Include audience stats placeholders and package tiers.']),
  mk('marketing', 'Seasonal Campaign Planner', 'seasonal or holiday campaign plan', undefined, ['Map key dates, offers, and creative themes.']),
  mk('marketing', 'Brand Partnership Evaluator', 'brand partnership fit assessment', undefined, ['Score alignment on audience, values, and goals.']),
  mk('marketing', 'Marketing Stack Recommender', 'marketing tech stack recommendations', undefined, ['Match tools to team size, budget, and goals.']),

  // Sales (30)
  mk('sales', 'Sales Funnel Architect', 'five-stage sales funnel with tactics per stage', undefined, ['Cover awareness, interest, decision, action, retention.']),
  mk('sales', 'Cold Outreach Email Writer', 'personalized cold outreach email sequence', undefined, ['Use problem-agitate-solution or value-first approach.']),
  mk('sales', 'Discovery Call Script', 'sales discovery call question guide', undefined, ['Uncover budget, authority, need, and timeline.']),
  mk('sales', 'Proposal Template Builder', 'client proposal structure and copy', undefined, ['Include scope, timeline, pricing, and terms sections.']),
  mk('sales', 'Objection Handling Guide', 'objection handling playbook with responses', undefined, ['Cover top 10 objections with empathetic rebuttals.']),
  mk('sales', 'Sales Deck Outline', 'persuasive sales presentation outline', undefined, ['Problem, solution, proof, offer, next steps.']),
  mk('sales', 'Lead Scoring Framework', 'lead scoring model with criteria', undefined, ['Weight behavioral and firmographic signals.']),
  mk('sales', 'Pipeline Review Template', 'weekly pipeline review agenda and report', undefined, ['Flag stalled deals and required actions.']),
  mk('sales', 'Upsell Strategy Planner', 'existing customer upsell and expansion plan', undefined, ['Segment by usage, satisfaction, and fit signals.']),
  mk('sales', 'Demo Script Creator', 'product demo script tailored to persona', undefined, ['Focus on outcomes not features; include discovery checkpoints.']),
  mk('sales', 'Negotiation Prep Worksheet', 'negotiation preparation worksheet', undefined, ['Define BATNA, walk-away point, and trade-offs.']),
  mk('sales', 'Account Plan Builder', 'strategic account plan for key clients', undefined, ['Map stakeholders, goals, risks, and growth opportunities.']),
  mk('sales', 'Sales Enablement One-Pager', 'sales enablement one-pager for reps', undefined, ['Summarize ICP, value prop, and top objections.']),
  mk('sales', 'Win-Loss Analysis Framework', 'win-loss interview question guide', undefined, ['Extract patterns for product and sales improvements.']),
  mk('sales', 'Territory Planning Guide', 'sales territory planning document', undefined, ['Prioritize accounts by potential and strategic fit.']),
  mk('sales', 'Referral Request Script', 'customer referral request templates', undefined, ['Make asking easy with suggested intro language.']),
  mk('sales', 'RFP Response Outline', 'RFP response structure and key sections', undefined, ['Address requirements systematically with proof points.']),
  mk('sales', 'Sales Compensation Model', 'sales compensation plan outline', undefined, ['Balance base, commission, accelerators, and caps.']),
  mk('sales', 'Channel Partner Pitch', 'channel partner recruitment pitch', undefined, ['Define mutual value, enablement, and economics.']),
  mk('sales', 'Renewal Risk Assessment', 'contract renewal risk assessment', undefined, ['Score health signals and mitigation actions.']),
  mk('sales', 'Sales Kickoff Agenda', 'sales kickoff meeting agenda and content plan', undefined, ['Align team on goals, messaging, and enablement.']),
  mk('sales', 'Competitive Battlecard', 'competitive sales battlecard', undefined, ['Compare strengths, weaknesses, and talk tracks.']),
  mk('sales', 'Outbound Call Script', 'outbound prospecting call script', undefined, ['Permission-based open; focus on curiosity not pitch.']),
  mk('sales', 'Quote Follow-Up Sequence', 'quote follow-up email sequence', undefined, ['Time follow-ups at 1, 3, and 7 days with varied angles.']),
  mk('sales', 'Sales Metrics Dashboard', 'sales KPI dashboard specification', undefined, ['Define leading and lagging indicators to track.']),
  mk('sales', 'Cross-Sell Playbook', 'cross-sell opportunity playbook', undefined, ['Map product adjacencies and trigger events.']),
  mk('sales', 'Enterprise Deal Strategy', 'enterprise deal pursuit strategy', undefined, ['Map buying committee and multi-threading plan.']),
  mk('sales', 'Sales Hiring Scorecard', 'sales candidate interview scorecard', undefined, ['Evaluate skills, culture fit, and coachability.']),
  mk('sales', 'Pricing Conversation Guide', 'pricing and discount conversation guide', undefined, ['Anchor on value; define discount approval rules.']),
  mk('sales', 'Customer Success Handoff Doc', 'sales-to-CS handoff document template', undefined, ['Transfer context, expectations, and success criteria.']),

  // SEO (25)
  mk('seo', 'Keyword Research Plan', 'keyword research report with clusters', undefined, ['Group by intent: informational, commercial, transactional.']),
  mk('seo', 'On-Page SEO Audit', 'on-page SEO audit checklist and fixes', undefined, ['Review titles, meta, headers, internal links, and content depth.']),
  mk('seo', 'Content Gap Analysis', 'content gap analysis vs competitors', undefined, ['Identify topics competitors rank for that you miss.']),
  mk('seo', 'Technical SEO Checklist', 'technical SEO audit checklist', undefined, ['Cover crawlability, indexation, Core Web Vitals, schema.']),
  mk('seo', 'Link Building Strategy', 'white-hat link building strategy', undefined, ['Prioritize tactics by effort and expected authority gain.']),
  mk('seo', 'Local SEO Action Plan', 'local SEO optimization plan', undefined, ['Google Business Profile, citations, local content, reviews.']),
  mk('seo', 'SEO Content Brief', 'SEO-optimized content brief for writers', undefined, ['Include target keyword, outline, and SERP analysis notes.']),
  mk('seo', 'Site Architecture Planner', 'SEO-friendly site architecture plan', undefined, ['Define hub pages, silos, and internal linking rules.']),
  mk('seo', 'Meta Description Batch Writer', 'meta title and description templates', undefined, ['Stay within character limits; include primary keyword naturally.']),
  mk('seo', 'Schema Markup Guide', 'schema markup implementation guide', undefined, ['Recommend types for this business and page templates.']),
  mk('seo', 'SEO Migration Checklist', 'website migration SEO preservation checklist', undefined, ['Redirects, sitemap, monitoring, and rollback plan.']),
  mk('seo', 'Featured Snippet Optimizer', 'featured snippet optimization plan', undefined, ['Format content for paragraph, list, and table snippets.']),
  mk('seo', 'International SEO Plan', 'international or multilingual SEO plan', undefined, ['Hreflang, URL structure, and localized content approach.']),
  mk('seo', 'E-commerce SEO Guide', 'e-commerce category and product page SEO guide', undefined, ['Faceted navigation, duplicate content, and PDP optimization.']),
  mk('seo', 'SEO Reporting Template', 'monthly SEO performance report template', undefined, ['Track rankings, traffic, conversions, and technical health.']),
  mk('seo', 'Blog Topic Cluster Plan', 'topic cluster and pillar page strategy', undefined, ['Map pillar page and supporting cluster articles.']),
  mk('seo', 'SERP Feature Strategy', 'SERP feature targeting strategy', undefined, ['Target People Also Ask, images, and video results.']),
  mk('seo', 'SEO Penalty Recovery Plan', 'search ranking recovery action plan', undefined, ['Diagnose manual actions or algorithm impacts.']),
  mk('seo', 'Programmatic SEO Blueprint', 'programmatic SEO page generation blueprint', undefined, ['Define templates, data sources, and quality guardrails.']),
  mk('seo', 'Voice Search Optimization', 'voice search optimization recommendations', undefined, ['Focus on conversational queries and FAQ structure.']),
  mk('seo', 'SEO Competitor Backlink Analysis', 'competitor backlink gap analysis', undefined, ['Identify link sources worth pursuing.']),
  mk('seo', 'URL Structure Guide', 'SEO-friendly URL structure guide', undefined, ['Consistent naming, hierarchy, and redirect rules.']),
  mk('seo', 'Content Refresh Prioritizer', 'content refresh priority list', undefined, ['Rank pages by traffic decay and ranking opportunity.']),
  mk('seo', 'SEO A/B Test Plan', 'SEO title and meta A/B test plan', undefined, ['Define variants, duration, and success metrics.']),
  mk('seo', 'Indexation Troubleshooter', 'indexation issue diagnostic guide', undefined, ['Check robots, canonicals, sitemap, and crawl budget.']),

  // Email (25)
  mk('email', 'Welcome Email Sequence', 'three-email welcome sequence', undefined, ['Email 1: welcome; Email 2: value; Email 3: CTA.']),
  mk('email', 'Cart Abandonment Series', 'cart abandonment recovery email series', undefined, ['Send at 1hr, 24hr, 72hr with escalating incentive options.']),
  mk('email', 'Newsletter Template Builder', 'weekly newsletter structure and sections', undefined, ['Balance curated links, original insight, and CTA.']),
  mk('email', 'Re-Engagement Campaign', 'win-back re-engagement email campaign', undefined, ['Segment inactive users; offer clear value or sunset path.']),
  mk('email', 'Product Launch Email Series', 'product launch announcement email series', undefined, ['Tease, launch, social proof, last chance sequence.']),
  mk('email', 'Lead Nurture Workflow', 'five-email lead nurture workflow', undefined, ['Educate, build trust, then present offer.']),
  mk('email', 'Transactional Email Optimizer', 'transactional email copy improvements', undefined, ['Improve clarity, upsell opportunities, and brand voice.']),
  mk('email', 'Survey Invitation Email', 'customer survey invitation email', undefined, ['Explain purpose, time required, and optional incentive.']),
  mk('email', 'Event Invitation Email', 'event invitation and reminder sequence', undefined, ['Include agenda highlights and registration urgency.']),
  mk('email', 'Post-Purchase Follow-Up', 'post-purchase thank-you and review request', undefined, ['Timing and tone optimized for satisfaction check first.']),
  mk('email', 'B2B Outreach Sequence', 'B2B cold email sequence with follow-ups', undefined, ['Keep emails under 150 words; one CTA each.']),
  mk('email', 'Email Subject Line Generator', '20 email subject line variations', undefined, ['Mix curiosity, benefit, personalization, and urgency.']),
  mk('email', 'Drip Campaign Architect', 'automated drip campaign map', undefined, ['Define triggers, delays, and branch conditions.']),
  mk('email', 'Email Segmentation Plan', 'email list segmentation strategy', undefined, ['Segment by behavior, lifecycle, and demographics.']),
  mk('email', 'Holiday Promo Email', 'holiday promotional email campaign', undefined, ['Align offer, creative theme, and send schedule.']),
  mk('email', 'Onboarding Email Series', 'user onboarding email series', undefined, ['Drive activation milestones in first 14 days.']),
  mk('email', 'Webinar Reminder Sequence', 'webinar reminder email sequence', undefined, ['Remind at 1 week, 1 day, 1 hour before start.']),
  mk('email', 'Customer Win-Back Offer', 'churned customer win-back email', undefined, ['Acknowledge absence; offer compelling return incentive.']),
  mk('email', 'Referral Email Template', 'customer referral request email', undefined, ['Make sharing frictionless with pre-written blurb.']),
  mk('email', 'Internal Update Email', 'team or stakeholder update email template', undefined, ['Lead with decisions needed; attach details below.']),
  mk('email', 'Partnership Announcement Email', 'partnership announcement email', undefined, ['Explain mutual benefit and customer impact.']),
  mk('email', 'Pricing Change Notice', 'pricing change communication email', undefined, ['Transparent rationale, grandfathering, and support offer.']),
  mk('email', 'Case Study Promo Email', 'case study promotion email', undefined, ['Highlight measurable results and relatable client profile.']),
  mk('email', 'VIP Customer Email', 'VIP or loyalty tier exclusive email', undefined, ['Early access, special pricing, or insider content angle.']),
  mk('email', 'Email Deliverability Audit', 'email deliverability improvement checklist', undefined, ['Review authentication, list hygiene, and content triggers.']),

  // Writing (30)
  mk('writing', 'Blog Post Outline Generator', 'SEO-ready blog post outline', undefined, ['Include H2/H3 structure, key points, and CTA placement.']),
  mk('writing', 'Long-Form Article Writer', 'long-form thought leadership article', undefined, ['Open with hook; support thesis with evidence and examples.']),
  mk('writing', 'White Paper Structure', 'B2B white paper structure and section guide', undefined, ['Executive summary, problem, solution, proof, CTA.']),
  mk('writing', 'Video Script Writer', 'YouTube or explainer video script', undefined, ['Hook, problem, solution, proof, CTA under target duration.']),
  mk('writing', 'Podcast Episode Outline', 'podcast episode outline with talking points', undefined, ['Segment intro, interview questions, and outro CTA.']),
  mk('writing', 'Social Thread Writer', 'LinkedIn or Twitter thread', undefined, ['One idea per post; strong hook on post 1.']),
  mk('writing', 'Product Description Writer', 'compelling product description copy', undefined, ['Benefits before features; address objections inline.']),
  mk('writing', 'About Page Copy', 'About Us page copy', undefined, ['Mission, story, team, proof, and conversion path.']),
  mk('writing', 'FAQ Page Generator', 'comprehensive FAQ page content', undefined, ['Order by customer journey and search intent.']),
  mk('writing', 'Testimonial Request Template', 'customer testimonial request templates', undefined, ['Provide guided questions for specific, measurable quotes.']),
  mk('writing', 'Executive Summary Writer', 'executive summary for reports or proposals', undefined, ['One page max; lead with recommendation.']),
  mk('writing', 'Technical Documentation Outline', 'technical documentation outline', undefined, ['Getting started, concepts, API/reference, troubleshooting.']),
  mk('writing', 'Grant Proposal Outline', 'grant or funding proposal outline', undefined, ['Align with funder priorities and evaluation criteria.']),
  mk('writing', 'Speech Writer', 'keynote or presentation speech draft', undefined, ['Story arc with clear takeaway and memorable close.']),
  mk('writing', 'Newsletter Intro Writer', 'engaging newsletter introduction paragraphs', undefined, ['Personal hook connecting to main content theme.']),
  mk('writing', 'Comparison Article Outline', 'product or solution comparison article', undefined, ['Fair criteria matrix; declare methodology transparently.']),
  mk('writing', 'Listicle Generator', 'numbered listicle article outline', undefined, ['Each item actionable with brief explanation.']),
  mk('writing', 'Glossary Builder', 'industry glossary for website or docs', undefined, ['Define terms plainly for target audience level.']),
  mk('writing', 'Customer Story Interview Guide', 'customer story interview question guide', undefined, ['Before, during, after transformation questions.']),
  mk('writing', 'Press Kit Writer', 'media press kit content outline', undefined, ['Boilerplate, facts, bios, assets, contact info.']),
  mk('writing', 'Mission Statement Refiner', 'refined mission and vision statements', undefined, ['Offer 3 variations: aspirational, practical, customer-centric.']),
  mk('writing', 'Job Description Writer', 'job description that attracts top talent', undefined, ['Lead with impact; inclusive language; clear requirements.']),
  mk('writing', 'Internal Memo Template', 'internal company memo template', undefined, ['Context, decision, rationale, next steps format.']),
  mk('writing', 'User Guide Writer', 'end-user product guide outline', undefined, ['Task-based sections with screenshots placeholders.']),
  mk('writing', 'Annual Report Narrative', 'annual report narrative sections', undefined, ['Highlights, challenges, outlook with data placeholders.']),
  mk('writing', 'Course Lesson Plan', 'online course lesson plan', undefined, ['Learning objectives, content, exercises, assessment.']),
  mk('writing', 'Book Chapter Outline', 'non-fiction book chapter outline', undefined, ['10-chapter arc with key arguments per chapter.']),
  mk('writing', 'Translation Style Guide', 'translation and localization style guide', undefined, ['Tone, terminology, regional preferences.']),
  mk('writing', 'Microcopy Pack', 'UI microcopy pack for key flows', undefined, ['Buttons, errors, empty states, success messages.']),
  mk('writing', 'Contrarian Essay Outline', 'contrarian opinion essay outline', undefined, ['Challenge conventional wisdom with evidence-backed thesis.']),

  // Business (35)
  mk('business', 'Business Plan Executive Summary', 'business plan executive summary', undefined, ['Problem, solution, market, traction, team, ask.']),
  mk('business', 'SWOT Analysis Generator', 'SWOT analysis with strategic implications', undefined, ['Translate each quadrant into actionable priorities.']),
  mk('business', 'OKR Framework Builder', 'quarterly OKR framework', undefined, ['3 objectives with 3-4 measurable key results each.']),
  mk('business', 'Meeting Agenda Creator', 'effective meeting agenda and facilitation guide', undefined, ['Pre-read, time boxes, decisions, action owners.']),
  mk('business', 'SOP Template Writer', 'standard operating procedure document', undefined, ['Purpose, scope, steps, quality checks, revision history.']),
  mk('business', 'Process Improvement Proposal', 'process improvement proposal', undefined, ['Current state, proposed state, ROI, implementation plan.']),
  mk('business', 'Vendor Evaluation Matrix', 'vendor selection evaluation matrix', undefined, ['Weighted criteria scoring with recommendation.']),
  mk('business', 'Risk Register Builder', 'project or business risk register', undefined, ['Likelihood, impact, mitigation, owner per risk.']),
  mk('business', 'Stakeholder Map', 'stakeholder analysis and engagement plan', undefined, ['Power/interest grid with communication strategy.']),
  mk('business', 'Business Model Canvas', 'business model canvas analysis', undefined, ['All nine blocks with assumptions flagged.']),
  mk('business', 'Pivot Decision Framework', 'business pivot evaluation framework', undefined, ['Signals, options, criteria, recommended path.']),
  mk('business', 'Board Update Template', 'board or investor update template', undefined, ['Metrics, wins, challenges, asks format.']),
  mk('business', 'Partnership Proposal', 'strategic partnership proposal', undefined, ['Mutual value, structure, timeline, success metrics.']),
  mk('business', 'Market Sizing Analysis', 'TAM SAM SOM market sizing analysis', undefined, ['State assumptions; top-down and bottom-up estimates.']),
  mk('business', 'Competitive Moat Analysis', 'competitive advantage and moat analysis', undefined, ['Assess durability of differentiation factors.']),
  mk('business', 'Pricing Strategy Guide', 'pricing strategy recommendation', undefined, ['Compare cost-plus, value-based, and competitive models.']),
  mk('business', 'Franchise Operations Manual Outline', 'franchise operations manual outline', undefined, ['Brand standards, operations, training, support sections.']),
  mk('business', 'Crisis Management Plan', 'business continuity and crisis plan', undefined, ['Scenarios, response teams, communication protocols.']),
  mk('business', 'KPI Dashboard Spec', 'business KPI dashboard specification', undefined, ['North star metric plus supporting indicators.']),
  mk('business', 'Delegation Framework', 'task delegation framework for leaders', undefined, ['Decision rights matrix: decide, consult, inform.']),
  mk('business', 'Team Charter Writer', 'team charter document', undefined, ['Purpose, norms, roles, communication cadence.']),
  mk('business', 'Annual Planning Template', 'annual strategic planning template', undefined, ['Review, priorities, budget, quarterly milestones.']),
  mk('business', 'Customer Advisory Board Plan', 'customer advisory board program plan', undefined, ['Recruitment, cadence, topics, incentives.']),
  mk('business', 'Innovation Workshop Facilitator', 'innovation workshop facilitation guide', undefined, ['Ideation, prioritization, and prototype next steps.']),
  mk('business', 'Exit Strategy Outline', 'business exit strategy outline', undefined, ['Options, valuation drivers, preparation timeline.']),
  mk('business', 'Supply Chain Risk Plan', 'supply chain risk mitigation plan', undefined, ['Single points of failure and backup suppliers.']),
  mk('business', 'Remote Work Policy', 'remote work policy draft', undefined, ['Expectations, tools, security, performance standards.']),
  mk('business', 'Change Management Plan', 'organizational change management plan', undefined, ['Stakeholders, communication, training, resistance handling.']),
  mk('business', 'Business Automation Audit', 'business automation opportunity audit', undefined, ['Map repetitive tasks to tool recommendations.']),
  mk('business', 'Investor Pitch Outline', 'investor pitch deck narrative outline', undefined, ['10-slide story arc with proof points per slide.']),
  mk('business', 'Franchisee Recruitment Plan', 'franchisee recruitment marketing plan', undefined, ['Ideal profile, channels, qualification process.']),
  mk('business', 'Quality Assurance Checklist', 'service quality assurance checklist', undefined, ['Standards, inspection frequency, corrective actions.']),
  mk('business', 'Merger Integration Plan', 'post-merger integration plan outline', undefined, ['Day 1, 30, 90, 180 day priorities.']),
  mk('business', 'ESG Reporting Outline', 'ESG reporting outline for stakeholders', undefined, ['Environmental, social, governance metrics framework.']),
  mk('business', 'Business Continuity Test Plan', 'business continuity drill test plan', undefined, ['Scenario, participants, success criteria, debrief.']),

  // HR (20)
  mk('hr', 'Job Interview Question Bank', 'structured interview question bank', undefined, ['Behavioral and situational questions by competency.']),
  mk('hr', 'Employee Onboarding Checklist', '30-60-90 day onboarding checklist', undefined, ['Pre-start, week 1, month 1, month 3 milestones.']),
  mk('hr', 'Performance Review Template', 'performance review conversation guide', undefined, ['Achievements, growth areas, goals, support needed.']),
  mk('hr', 'Employer Brand Content Plan', 'employer branding content plan', undefined, ['Culture stories, employee spotlights, values in action.']),
  mk('hr', 'Compensation Benchmark Guide', 'compensation benchmarking approach', undefined, ['Role leveling, market data sources, pay bands.']),
  mk('hr', 'DEI Initiative Planner', 'diversity and inclusion initiative plan', undefined, ['Goals, programs, metrics, accountability structure.']),
  mk('hr', 'Exit Interview Guide', 'exit interview question guide', undefined, ['Extract actionable retention insights.']),
  mk('hr', 'Training Needs Assessment', 'training needs assessment framework', undefined, ['Skill gaps, priority programs, delivery methods.']),
  mk('hr', 'Employee Handbook Outline', 'employee handbook section outline', undefined, ['Policies, benefits, conduct, grievance procedures.']),
  mk('hr', 'Recruitment Marketing Copy', 'job ad and recruitment marketing copy', undefined, ['Compelling role pitch with inclusive language.']),
  mk('hr', 'Team Building Activity Plan', 'team building session plan', undefined, ['Objective, activity, debrief, follow-up actions.']),
  mk('hr', 'Succession Planning Template', 'succession planning template for key roles', undefined, ['Identify successors, readiness, development plans.']),
  mk('hr', 'Employee Engagement Survey', 'employee engagement survey design', undefined, ['10-15 questions across drivers of engagement.']),
  mk('hr', 'Remote Hiring Process', 'remote hiring process and evaluation guide', undefined, ['Async steps, live interviews, work sample tests.']),
  mk('hr', 'Benefits Communication Guide', 'employee benefits communication guide', undefined, ['Plain-language explanations and enrollment tips.']),
  mk('hr', 'Conflict Resolution Script', 'workplace conflict mediation script', undefined, ['Neutral facilitation steps and ground rules.']),
  mk('hr', 'Internship Program Design', 'internship program structure and goals', undefined, ['Projects, mentorship, evaluation, conversion path.']),
  mk('hr', 'Skills Matrix Builder', 'team skills matrix template', undefined, ['Map current vs required skills; training priorities.']),
  mk('hr', 'Offboarding Checklist', 'employee offboarding checklist', undefined, ['Access revocation, knowledge transfer, exit interview.']),
  mk('hr', 'Culture Values Workshop', 'company values definition workshop guide', undefined, ['Facilitation steps to define and operationalize values.']),

  // Finance (15)
  mk('finance', 'Cash Flow Forecast', '13-week cash flow forecast template', undefined, ['Inflows, outflows, assumptions, runway calculation.']),
  mk('finance', 'Budget Planning Guide', 'annual budget planning guide', undefined, ['Revenue drivers, cost categories, variance process.']),
  mk('finance', 'Unit Economics Calculator', 'unit economics analysis framework', undefined, ['CAC, LTV, payback period, contribution margin.']),
  mk('finance', 'Financial Model Outline', 'startup financial model structure', undefined, ['Assumptions tab, P&L, cash flow, balance sheet logic.']),
  mk('finance', 'Expense Audit Checklist', 'operating expense audit checklist', undefined, ['Identify cuts without harming growth drivers.']),
  mk('finance', 'Fundraising Use of Funds', 'investor use-of-funds breakdown', undefined, ['Allocate by milestone with timeline.']),
  mk('finance', 'Pricing Sensitivity Analysis', 'pricing sensitivity analysis guide', undefined, ['Model volume and revenue impact of price changes.']),
  mk('finance', 'Break-Even Analysis', 'break-even analysis report', undefined, ['Fixed vs variable costs; units and revenue breakeven.']),
  mk('finance', 'Accounts Receivable Plan', 'accounts receivable collection plan', undefined, ['Aging buckets, follow-up cadence, escalation rules.']),
  mk('finance', 'Tax Planning Checklist', 'small business tax planning checklist', undefined, ['Deductions, estimated payments, entity considerations.']),
  mk('finance', 'Investor Metrics Report', 'investor metrics reporting template', undefined, ['MRR, churn, burn, runway, cohort highlights.']),
  mk('finance', 'Scenario Planning Model', 'best/base/worst scenario financial plan', undefined, ['Define triggers and response actions per scenario.']),
  mk('finance', 'Cap Table Explainer', 'cap table and dilution explainer outline', undefined, ['Plain-language guide for founders and employees.']),
  mk('finance', 'Vendor Payment Terms Negotiator', 'vendor payment terms negotiation guide', undefined, ['Net terms, discounts, and cash flow impact.']),
  mk('finance', 'Profitability by Segment', 'segment profitability analysis framework', undefined, ['Allocate costs; rank segments by margin.']),

  // Legal (12)
  mk('legal', 'Contract Review Checklist', 'commercial contract review checklist', undefined, ['Key clauses: liability, termination, IP, payment.']),
  mk('legal', 'Privacy Policy Outline', 'website privacy policy outline', undefined, ['Data collected, use, sharing, rights, contact.']),
  mk('legal', 'Terms of Service Draft Guide', 'terms of service structure guide', undefined, ['User obligations, limitations, dispute resolution.']),
  mk('legal', 'NDA Template Guide', 'mutual NDA key terms guide', undefined, ['Scope, duration, exclusions, remedies.']),
  mk('legal', 'Employment Agreement Outline', 'employment agreement key terms outline', undefined, ['Role, comp, IP assignment, confidentiality, termination.']),
  mk('legal', 'GDPR Compliance Checklist', 'GDPR compliance checklist for businesses', undefined, ['Lawful basis, rights, DPA, breach procedures.']),
  mk('legal', 'IP Protection Guide', 'intellectual property protection guide', undefined, ['Trademarks, copyrights, trade secrets checklist.']),
  mk('legal', 'Vendor Contract Template', 'vendor services agreement outline', undefined, ['SLAs, liability caps, data handling, exit terms.']),
  mk('legal', 'Disclaimer Language Guide', 'website and content disclaimer language guide', undefined, ['Limit liability appropriately for content type.']),
  mk('legal', 'Compliance Training Outline', 'regulatory compliance training outline', undefined, ['Topics, scenarios, assessment, record-keeping.']),
  mk('legal', 'Dispute Resolution Clause Guide', 'dispute resolution clause options guide', undefined, ['Negotiation, mediation, arbitration comparison.']),
  mk('legal', 'Cookie Policy Writer', 'cookie policy and consent banner guide', undefined, ['Cookie types, purposes, opt-out mechanisms.']),

  // Customer Service (20)
  mk('customer-service', 'Support Macro Library', 'customer support response macro library', undefined, ['Cover top 15 ticket types with empathetic tone.']),
  mk('customer-service', 'Escalation Playbook', 'support escalation playbook', undefined, ['Tiers, SLAs, handoff criteria, documentation rules.']),
  mk('customer-service', 'CSAT Improvement Plan', 'customer satisfaction improvement plan', undefined, ['Root cause themes and targeted fixes.']),
  mk('customer-service', 'Help Center Structure', 'help center taxonomy and article plan', undefined, ['Categories, top articles, search optimization.']),
  mk('customer-service', 'Chatbot Script Designer', 'support chatbot conversation script', undefined, ['Intent detection, fallback to human, tone guidelines.']),
  mk('customer-service', 'Complaint Resolution Script', 'customer complaint resolution script', undefined, ['Listen, apologize, solve, follow-up framework.']),
  mk('customer-service', 'SLA Policy Writer', 'customer support SLA policy document', undefined, ['Response and resolution times by priority tier.']),
  mk('customer-service', 'Knowledge Base Article', 'support knowledge base article template', undefined, ['Problem, steps, verification, related articles.']),
  mk('customer-service', 'Refund Policy Communicator', 'refund request response templates', undefined, ['Policy-aligned empathetic responses.']),
  mk('customer-service', 'VIP Support Protocol', 'VIP customer support protocol', undefined, ['Identification rules, white-glove handling steps.']),
  mk('customer-service', 'Support Team Training Plan', 'new support agent training plan', undefined, ['Product, tools, tone, escalation in first 2 weeks.']),
  mk('customer-service', 'Proactive Outreach Template', 'proactive customer outreach messages', undefined, ['Check-ins before issues arise; value-add touchpoints.']),
  mk('customer-service', 'Bug Report Triage Guide', 'customer bug report triage guide', undefined, ['Reproduce, severity, workaround, customer update cadence.']),
  mk('customer-service', 'Social Support Response Guide', 'social media support response guide', undefined, ['Public vs DM handling; de-escalation language.']),
  mk('customer-service', 'Customer Feedback Loop', 'closing the customer feedback loop process', undefined, ['Collect, categorize, act, notify customers of fixes.']),
  mk('customer-service', 'Support Metrics Dashboard', 'support team metrics dashboard spec', undefined, ['CSAT, FRT, ART, backlog, agent performance.']),
  mk('customer-service', 'Multilingual Support Guide', 'multilingual customer support guidelines', undefined, ['Translation workflow and quality standards.']),
  mk('customer-service', 'Cancellation Save Script', 'subscription cancellation save conversation script', undefined, ['Understand reason; offer targeted retention options.']),
  mk('customer-service', 'Onboarding Support Plan', 'new customer onboarding support plan', undefined, ['Touchpoints in first 30 days to prevent churn.']),
  mk('customer-service', 'Support Quality Audit', 'support conversation quality audit rubric', undefined, ['Score empathy, accuracy, resolution, efficiency.']),

  // E-commerce (25)
  mk('ecommerce', 'Product Page Optimizer', 'e-commerce product page optimization guide', undefined, ['Images, copy, reviews, urgency, cross-sells.']),
  mk('ecommerce', 'Checkout Flow Audit', 'checkout flow conversion audit', undefined, ['Friction points, trust signals, payment options.']),
  mk('ecommerce', 'Amazon Listing Optimizer', 'Amazon product listing optimization guide', undefined, ['Title, bullets, A+ content, backend keywords.']),
  mk('ecommerce', 'Shopify Store Audit', 'Shopify store optimization checklist', undefined, ['Theme, apps, speed, collections, SEO.']),
  mk('ecommerce', 'Promotional Calendar', 'e-commerce promotional calendar', undefined, ['Sales events, bundles, email/SMS coordination.']),
  mk('ecommerce', 'Inventory Planning Guide', 'inventory planning and reorder guide', undefined, ['Lead times, safety stock, seasonality factors.']),
  mk('ecommerce', 'Return Policy Optimizer', 'return policy that balances trust and cost', undefined, ['Clear terms; reduce unnecessary returns.']),
  mk('ecommerce', 'Upsell Cross-Sell Strategy', 'post-add-to-cart upsell strategy', undefined, ['Complementary products and bundle offers.']),
  mk('ecommerce', 'Review Generation Plan', 'product review generation campaign', undefined, ['Timing, incentives, platform syndication.']),
  mk('ecommerce', 'Shipping Policy Writer', 'shipping and delivery policy copy', undefined, ['Rates, timelines, international, free shipping thresholds.']),
  mk('ecommerce', 'Category Page SEO', 'e-commerce category page optimization', undefined, ['Intro copy, filters, internal linking, schema.']),
  mk('ecommerce', 'Loyalty Program Design', 'customer loyalty program design', undefined, ['Points, tiers, rewards, redemption rules.']),
  mk('ecommerce', 'Abandoned Browse Campaign', 'browse abandonment email strategy', undefined, ['Trigger rules and product recommendation logic.']),
  mk('ecommerce', 'Wholesale Channel Plan', 'wholesale or B2B channel launch plan', undefined, ['Pricing, MOQ, terms, buyer outreach.']),
  mk('ecommerce', 'Marketplace Expansion Guide', 'marketplace expansion strategy', undefined, ['Evaluate Amazon, Etsy, Walmart fit and ops requirements.']),
  mk('ecommerce', 'Product Launch Checklist', 'e-commerce product launch checklist', undefined, ['Listing, ads, email, influencers, inventory ready.']),
  mk('ecommerce', 'Customer Segmentation RFM', 'RFM customer segmentation analysis guide', undefined, ['Recency, frequency, monetary scoring and campaigns.']),
  mk('ecommerce', 'Subscription Box Planner', 'subscription box offer planning guide', undefined, ['Pricing, cadence, churn prevention tactics.']),
  mk('ecommerce', 'Flash Sale Playbook', 'flash sale execution playbook', undefined, ['Inventory, pricing, urgency, support staffing.']),
  mk('ecommerce', 'Gift Guide Creator', 'seasonal gift guide content plan', undefined, ['Curated collections by recipient and budget.']),
  mk('ecommerce', 'Dropshipping Supplier Eval', 'dropshipping supplier evaluation checklist', undefined, ['Quality, shipping speed, communication, samples.']),
  mk('ecommerce', 'Cart Value Optimizer', 'average order value improvement plan', undefined, ['Bundles, thresholds, recommendations, urgency.']),
  mk('ecommerce', 'E-commerce Analytics Setup', 'e-commerce analytics tracking setup guide', undefined, ['Events, funnels, attribution, reporting views.']),
  mk('ecommerce', 'International Expansion Plan', 'international e-commerce expansion plan', undefined, ['Payments, shipping, duties, localization.']),
  mk('ecommerce', 'Post-Purchase Experience', 'post-purchase unboxing and retention plan', undefined, ['Packaging, inserts, referral prompts, replenishment.']),

  // Productivity (25)
  mk('productivity', 'Weekly Planning Template', 'weekly planning and prioritization template', undefined, ['Top 3 priorities, time blocks, review ritual.']),
  mk('productivity', 'Meeting Reduction Audit', 'meeting audit and reduction plan', undefined, ['Which to cut, shorten, or make async.']),
  mk('productivity', 'Automation Workflow Designer', 'no-code automation workflow design', undefined, ['Trigger, steps, tools (Zapier/Make/n8n), error handling.']),
  mk('productivity', 'Inbox Zero System', 'email processing and inbox management system', undefined, ['Folders, rules, response templates, batch schedule.']),
  mk('productivity', 'Project Kickoff Checklist', 'project kickoff checklist and charter', undefined, ['Scope, roles, timeline, risks, communication plan.']),
  mk('productivity', 'Time Audit Analyzer', 'personal or team time audit analysis', undefined, ['Categorize activities; identify delegation opportunities.']),
  mk('productivity', 'Notion Workspace Architect', 'Notion workspace structure design', undefined, ['Databases, views, templates for team workflows.']),
  mk('productivity', 'Daily Standup Facilitator', 'async daily standup format and questions', undefined, ['Yesterday, today, blockers — keep under 5 min.']),
  mk('productivity', 'Documentation System', 'team documentation system design', undefined, ['Where docs live, templates, review cadence.']),
  mk('productivity', 'Handoff Checklist', 'role or project handoff checklist', undefined, ['Access, contacts, open items, context doc.']),
  mk('productivity', 'Focus Block Scheduler', 'deep work focus block schedule design', undefined, ['Calendar rules, interruption protocols, metrics.']),
  mk('productivity', 'Retrospective Facilitator', 'sprint or project retrospective guide', undefined, ['Start/stop/continue format with action owners.']),
  mk('productivity', 'Tool Stack Audit', 'SaaS tool stack audit and consolidation plan', undefined, ['Overlap, cost, usage, keep/kill/replace decisions.']),
  mk('productivity', 'Decision Log Template', 'team decision log template', undefined, ['Decision, rationale, date, owner, review date.']),
  mk('productivity', 'Async Communication Guide', 'async-first communication guidelines', undefined, ['When to write vs meet; response time expectations.']),
  mk('productivity', 'Goal Tracking System', 'personal or team goal tracking system', undefined, ['Weekly review ritual and progress visualization.']),
  mk('productivity', 'Batch Processing Planner', 'task batching schedule for repetitive work', undefined, ['Group similar tasks; protect batch time blocks.']),
  mk('productivity', 'Client Onboarding Workflow', 'client onboarding workflow automation map', undefined, ['Forms, contracts, welcome sequence, kickoff call.']),
  mk('productivity', 'Energy Management Plan', 'personal energy management plan', undefined, ['Match task types to peak energy windows.']),
  mk('productivity', 'Second Brain Setup', 'personal knowledge management system setup', undefined, ['Capture, organize, distill, express workflow.']),
  mk('productivity', 'Quarterly Review Template', 'quarterly personal or business review template', undefined, ['Wins, lessons, priorities for next quarter.']),
  mk('productivity', 'Workflow Bottleneck Finder', 'workflow bottleneck analysis', undefined, ['Map process; identify constraints and fixes.']),
  mk('productivity', 'Template Library Builder', 'reusable template library structure', undefined, ['Categories, naming, version control, access.']),
  mk('productivity', 'Focus Problem Solver', 'structured problem-solving worksheet', undefined, ['Define, analyze, options, decide, act framework.']),
  mk('productivity', 'Calendar Optimization Plan', 'calendar optimization for managers', undefined, ['Theme days, office hours, no-meeting blocks.']),

  // Social Media (25)
  mk('social-media', 'Content Pillar Strategy', 'social media content pillar strategy', undefined, ['3-5 pillars with example post types each.']),
  mk('social-media', 'Instagram Reels Script', 'Instagram Reels script and shot list', undefined, ['Hook, value, CTA in under 60 seconds.']),
  mk('social-media', 'LinkedIn Growth Plan', 'LinkedIn personal brand growth plan', undefined, ['Posting cadence, content mix, engagement tactics.']),
  mk('social-media', 'TikTok Content Calendar', 'TikTok content calendar with trend slots', undefined, ['Balance evergreen and trend-jacking content.']),
  mk('social-media', 'Community Management Guide', 'social community management playbook', undefined, ['Response times, moderation rules, escalation.']),
  mk('social-media', 'Influencer Campaign Brief', 'micro-influencer campaign brief', undefined, ['Deliverables, hashtags, disclosure, usage rights.']),
  mk('social-media', 'Social Ad Creative Brief', 'paid social ad creative brief', undefined, ['Objective, audience, formats, hooks to test.']),
  mk('social-media', 'Hashtag Strategy Guide', 'hashtag research and strategy guide', undefined, ['Branded, community, and discovery hashtags.']),
  mk('social-media', 'UGC Campaign Planner', 'user-generated content campaign plan', undefined, ['Prompt, incentive, rights, amplification.']),
  mk('social-media', 'Platform Launch Plan', 'new social platform launch plan', undefined, ['Profile setup, content backlog, cross-promotion.']),
  mk('social-media', 'Crisis Response Protocol', 'social media crisis response protocol', undefined, ['Monitor, assess, respond, escalate, post-mortem.']),
  mk('social-media', 'Analytics Report Template', 'monthly social media analytics report', undefined, ['Reach, engagement, conversions, top content.']),
  mk('social-media', 'Carousel Post Designer', 'educational carousel post outline', undefined, ['Slide-by-slide copy with strong cover slide.']),
  mk('social-media', 'Live Stream Run of Show', 'live stream run-of-show document', undefined, ['Segments, talking points, CTAs, moderation plan.']),
  mk('social-media', 'Social Listening Setup', 'social listening and monitoring setup', undefined, ['Keywords, tools, alert rules, response workflow.']),
  mk('social-media', 'Employee Advocacy Program', 'employee advocacy program design', undefined, ['Guidelines, content library, gamification options.']),
  mk('social-media', 'Pinterest SEO Strategy', 'Pinterest SEO and pin strategy', undefined, ['Boards, pin descriptions, seasonal planning.']),
  mk('social-media', 'YouTube Channel Strategy', 'YouTube channel growth strategy', undefined, ['Niche, formats, upload schedule, thumbnail style.']),
  mk('social-media', 'Social Proof Collection Plan', 'social proof collection and repurposing plan', undefined, ['Reviews, screenshots, testimonials across platforms.']),
  mk('social-media', 'Cross-Platform Repurposing', 'content repurposing workflow across platforms', undefined, ['One pillar piece to 10+ social assets map.']),
  mk('social-media', 'Engagement Pod Alternative', 'authentic engagement growth tactics', undefined, ['Ethical alternatives to engagement pods.']),
  mk('social-media', 'Bio Optimization Guide', 'social profile bio optimization guide', undefined, ['Clear value prop, CTA, link strategy.']),
  mk('social-media', 'Story Sequence Planner', 'Instagram/Facebook story sequence planner', undefined, ['Narrative arc across 5-10 story frames.']),
  mk('social-media', 'Social Commerce Setup', 'social commerce shop setup guide', undefined, ['Catalog, checkout, tagging products in posts.']),
  mk('social-media', 'Brand Ambassador Program', 'brand ambassador program structure', undefined, ['Recruitment, perks, content expectations, tracking.']),

  // Coding (20)
  mk('coding', 'API Design Review', 'REST API design review checklist', undefined, ['Resources, methods, errors, versioning, auth.']),
  mk('coding', 'Code Review Checklist', 'pull request code review checklist', undefined, ['Logic, tests, security, performance, readability.']),
  mk('coding', 'Bug Triage Guide', 'software bug triage and prioritization guide', undefined, ['Severity, reproducibility, user impact scoring.']),
  mk('coding', 'Technical Spec Writer', 'technical specification document outline', undefined, ['Problem, proposal, alternatives, rollout plan.']),
  mk('coding', 'Refactoring Plan', 'legacy code refactoring plan', undefined, ['Scope, tests first, incremental steps, rollback.']),
  mk('coding', 'Database Schema Review', 'database schema design review', undefined, ['Normalization, indexes, naming, migration strategy.']),
  mk('coding', 'Security Audit Checklist', 'application security audit checklist', undefined, ['OWASP top 10, auth, input validation, secrets.']),
  mk('coding', 'CI/CD Pipeline Design', 'CI/CD pipeline design document', undefined, ['Stages, gates, environments, rollback procedures.']),
  mk('coding', 'Performance Optimization Plan', 'application performance optimization plan', undefined, ['Profile, bottleneck, fix, measure cycle.']),
  mk('coding', 'Microservices Decomposition', 'monolith to microservices decomposition plan', undefined, ['Bounded contexts, migration order, data strategy.']),
  mk('coding', 'Test Strategy Document', 'software test strategy document', undefined, ['Unit, integration, e2e coverage targets and tools.']),
  mk('coding', 'Incident Postmortem Template', 'incident postmortem report template', undefined, ['Timeline, root cause, action items, blameless tone.']),
  mk('coding', 'Documentation Generator Guide', 'API documentation generation guide', undefined, ['OpenAPI, examples, auth docs, changelog.']),
  mk('coding', 'Tech Debt Prioritizer', 'technical debt prioritization framework', undefined, ['Impact, effort, risk scoring for paydown order.']),
  mk('coding', 'Architecture Decision Record', 'architecture decision record template', undefined, ['Context, decision, consequences, status.']),
  mk('coding', 'Onboarding Dev Guide', 'developer onboarding guide for codebase', undefined, ['Setup, architecture tour, first PR path.']),
  mk('coding', 'SQL Query Optimizer', 'SQL query optimization review guide', undefined, ['Explain plans, indexes, query rewrites.']),
  mk('coding', 'Feature Flag Strategy', 'feature flag rollout strategy', undefined, ['Naming, targeting, cleanup, kill switches.']),
  mk('coding', 'Logging Standards Guide', 'application logging and observability standards', undefined, ['Levels, structured fields, PII rules, alerts.']),
  mk('coding', 'Mobile App Release Checklist', 'mobile app release checklist', undefined, ['QA, store assets, phased rollout, monitoring.']),

  // Real Estate (12)
  mk('real-estate', 'Listing Description Writer', 'property listing description copy', undefined, ['Highlight features, neighborhood, lifestyle benefits.']),
  mk('real-estate', 'Open House Marketing Plan', 'open house marketing and follow-up plan', undefined, ['Promotion channels, signage, agent script, leads.']),
  mk('real-estate', 'Buyer Consultation Script', 'buyer consultation meeting script', undefined, ['Needs assessment, pre-approval, search criteria.']),
  mk('real-estate', 'Seller CMA Presentation', 'comparative market analysis presentation outline', undefined, ['Comps, pricing strategy, marketing plan preview.']),
  mk('real-estate', 'Real Estate SEO Plan', 'real estate agent local SEO plan', undefined, ['Neighborhood pages, GMB, reviews, content topics.']),
  mk('real-estate', 'Investor Deal Analyzer', 'rental property deal analysis framework', undefined, ['Cap rate, cash-on-cash, expenses, assumptions.']),
  mk('real-estate', 'Tenant Screening Guide', 'residential tenant screening checklist', undefined, ['Application, credit, references, fair housing compliance.']),
  mk('real-estate', 'Property Management SOP', 'property management standard procedures outline', undefined, ['Leasing, maintenance, accounting, communications.']),
  mk('real-estate', 'Real Estate Newsletter', 'real estate client newsletter template', undefined, ['Market update, listings, tips, local events.']),
  mk('real-estate', 'Commercial Lease Summary', 'commercial lease key terms summary guide', undefined, ['Rent, term, CAM, options, termination clauses.']),
  mk('real-estate', 'Staging Recommendation Guide', 'home staging recommendation guide', undefined, ['Room-by-room priorities for maximum appeal.']),
  mk('real-estate', 'Real Estate Social Content', 'real estate social media content calendar', undefined, ['Listings, market stats, tips, personal brand posts.']),
]
