#!/usr/bin/env npx tsx
/**
 * Sync prompts-db.json into src/data/prompts.generated.ts for the web app
 */

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath, pathToFileURL } from 'url'
import type { PromptsDatabase } from '../scraper/types.ts'
import type { Prompt } from '../../src/types/prompt.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DB_PATH = join(__dirname, '../data/prompts-db.json')
const SEED_PATH = join(__dirname, '../src/data/prompts.seed.ts')
const OUT_PATH = join(__dirname, '../src/data/prompts.generated.ts')

function stripSource(prompt: Prompt & { source?: unknown }): Prompt {
  const { source: _, ...rest } = prompt as Prompt & { source?: unknown }
  return rest
}

function dedupeByTitle(prompts: Prompt[]): Prompt[] {
  const seen = new Set<string>()
  return prompts.filter((p) => {
    const key = p.title.toLowerCase()
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
}

async function main() {
  const seedModule = await import(pathToFileURL(SEED_PATH).href)
  const seedPrompts: Prompt[] = seedModule.prompts

  let scraped: Prompt[] = []
  try {
    const db = JSON.parse(readFileSync(DB_PATH, 'utf-8')) as PromptsDatabase
    scraped = db.prompts.map(stripSource)
    console.log(`Loaded ${scraped.length} scraped prompts from database`)
  } catch {
    console.log('No prompts-db.json found, using seed prompts only')
  }

  const merged = dedupeByTitle([...seedPrompts, ...scraped])
  console.log(`Merged total: ${merged.length} prompts (${seedPrompts.length} seed + ${scraped.length} scraped)`)

  const output = `// AUTO-GENERATED by scripts/build-prompts.ts — do not edit manually
import type { Prompt } from '../types/prompt'

export const prompts: Prompt[] = ${JSON.stringify(merged, null, 2)} as Prompt[]

export const promptCount = ${merged.length}
export const scrapedCount = ${scraped.length}
export const seedCount = ${seedPrompts.length}
`

  writeFileSync(OUT_PATH, output, 'utf-8')
  console.log(`✅ Written to src/data/prompts.generated.ts`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
