#!/usr/bin/env python3
"""Generate website/public/api/config.php from .env (never commit config.php)."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV = ROOT / ".env"
OUT = ROOT / "website/public/api/config.php"
EXAMPLE = ROOT / "website/public/api/config.example.php"


def load_env() -> dict[str, str]:
    data: dict[str, str] = {}
    if not ENV.exists():
        return data
    for line in ENV.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        data[k.strip()] = v.strip().strip('"').strip("'")
    return data


def php_str(value: str | None) -> str:
    if value is None or value == "":
        return "null"
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def main() -> int:
    env = load_env()
    gemini = env.get("GEMINI_API_KEY") or None
    webhook = env.get("ESP_WEBHOOK_URL") or env.get("WEBHOOK_URL") or None
    checkout = env.get("STRIPE_CHECKOUT_URL") or env.get("CHECKOUT_URL") or None
    mail_from = env.get("MAIL_FROM") or "briefings@freemanintelligence.com"
    mail_reply = env.get("MAIL_REPLY_TO") or "samuel@freemanintelligence.com"
    gemini_model = env.get("GEMINI_MODEL") or "gemini-2.0-flash"

    content = f"""<?php
// Generated by scripts/generate-public-api-config.py — do not commit
return [
    'webhook_url' => {php_str(webhook)},
    'checkout_url' => {php_str(checkout)},

    'mail_from' => {php_str(mail_from)},
    'mail_from_name' => 'Freeman Intelligence',
    'mail_reply_to' => {php_str(mail_reply)},

    'gemini_api_key' => {php_str(gemini)},
    'gemini_model' => {php_str(gemini_model)},
];
"""
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"  gemini_api_key: {'set' if gemini else 'MISSING'}")
    print(f"  mail_from: {mail_from}")
    print(f"  webhook_url: {'set' if webhook else 'null'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
